# 登录时的更新通知
# 当没有网络连接时可以禁用
update-notify: true

# 自动保存玩家数据的时间间隔。
# 编辑后需要重新加载
auto-save:
  enabled: true
  interval: 1800 # 以秒为单位（1800 = 30分钟）
  log: true

# 当数据从SQL数据库中保存/加载时，将在控制台上显示详细信息。
debug: false

# MySQL支持
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: minecraft
  user: mmolover
  pass: ILoveAria
  properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

# 存货栏槽位的数量 - 必须是9的倍数。
# 在更改此选项后，请记得更新items.yml中的槽位编号。
inventory-slots: 36

# 启用此选项可将装备栏槽位移到玩家的
# 存货栏。资源页面提供了一个教程。
# 更改后需要重新加载服务器。
no-custom-inventory: false

# 这将防止已知的重复物品漏洞，因此强烈建议将其设置为true。
disable-equiping-stacked-items: true

# 物品在死亡时会掉落（当keep-inventory被禁用时）。
# 更改后需要重新加载服务器。
drop-on-death: true

# 可用的模块：
# - aureliumskills（仅级别）
# - battlelevels（仅级别）
# - default（使用玩家的经验条，仅级别）
# - heroes
# - mcmmo（仅级别）
# - mcrpg（仅级别）
# - mmocore
# - proskillapi
# - racesandclasses
# - rpgplayerleveling（仅级别）
# - skillapi
# - skills
# - skillspro
level-module: default
class-module: default

# 向玩家的存货栏添加静态按钮。
# 点击时打开自定义存货栏。
# 更改后需要重新加载服务器。
inventory-button:
  enabled: false
  slot: 9
  item:
    material: CHEST
    name: '&6自定义存货栏'
    lore:
      - ''
      - '&e点击以打开。'
    # custom-model-data: 1
    # skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg5Yjk4ZjA0YzMyMjdkMzdkMzE5YmJjZmZjNTFmNTJlNzhkOTZhMDViMTI4NTJkMWI0NjRiYjc0MDhhNzgxMCJ9fX0=

# 启用/禁用自动资源包下载。更改后需要重新加载服务器。
# 默认RP：https://www.dropbox.com/s/1lftxmzh0q4b5yu/mmoinv_rp_4.zip?dl=1
resource-pack:
  enabled: true
  url: resource_pack_url
  delay: 20

  # 如果玩家不接受服务器资源包或
  # 下载失败，将踢出玩家。更改后需要重新加载服务器。
  kick:
    enabled: false
    message: '请接受服务器资源包！'
