name: RPGInventory
version: ${project.version}
main: net.Indyuce.inventory.MMOInventory
author: Indyuce
description: ${project.description}
softdepend: [MMOItems,MMOProfiles]
depend: [MythicLib]
api-version: 1.13
commands:
  mmoinventory:
    description: 打开自定义存货栏。
    aliases: [rpginventory, mmoinv, rpginv]

permissions:
  mmoinventory.open:
    description: 允许使用命令打开自己的存货栏。
    default: op
  mmoinventory.open.other:
    description: 允许打开其他玩家的存货栏。
    default: op
  mmoinventory.admin:
    description: 允许使用管理员命令。
    default: op
